apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: demo-apps
  labels:
    app: app1
spec:
  containers:
    - name: app1
      image: busybox
      command: ["sh", "-c", "while true; do echo Hello from App1; sleep 5; done"]
